Binlandorg/binland-website-client

index.html
package-lock.json
package.json
src/App.tsx
src/components/Hero/Hero.tsx
src/hooks/useIntlMessages.ts
src/lang/en.json
src/lang/es.json
src/ui/Container/Container.tsx
src/ui/Section/Section.tsx
tsconfig.json

- Intl hook for translation 
- the basic structure of the page

feat: Intl hook for translation & basic structure of the page

---

src/pages/ContactUs/ContactUs.tsx
src/ui/Textarea/Textarea.styles.ts
src/ui/Textarea/Textarea.tsx

onChange and Value I made optional for now, it will be modified when the form is created.
Check it out!

add: textarea-component

---

package-lock.json
package.json
src/lang/en.json
src/lang/es.json
src/pages/ContactUs/ContactUs.tsx
src/pages/ContactUs/calendly.css

the button to schedule a meeting in calendly was added

integrate calendly

---

src/components/LanguageSwitcher/LanguageSwitcher.tsx
src/components/Navbar/Navbar.tsx
src/context/Language/langConfig.ts
src/ui/Button/Button.tsx
src/ui/ButtonLink/ButtonLink.tsx
src/ui/Select/Select.styles.ts
src/ui/Select/Select.tsx

check it out and let me know if you have any recommendations

redesign styles of select

---

src/components/Footer/Footer.data.tsx
src/components/Footer/Footer.styles.ts
src/components/Footer/Footer.tsx

implement socialmedia and correct arrays of links

---

src/ui/Button/Button.styles.ts
src/ui/Button/Button.tsx
src/ui/Container/Container.styles.ts
src/ui/Container/Container.tsx
src/ui/MultiSelect/MultiSelect.styles.ts
src/ui/MultiSelect/MultiSelect.tsx

warnings props fixed

---

src/components/Clients/Clients.styles.ts
src/components/Clients/Clients.tsx
src/pages/Home/Home.tsx

fix clients section

---

src/components/FaqCard/FaqCard.styles.ts
src/components/FaqCard/FaqCard.tsx
src/components/StillHaveQuestion/StillHaveQuestion.styles.ts
src/components/StillHaveQuestion/StillHaveQuestion.tsx
src/pages/FrequentlyAskedQuestion/FrequentlyAskedQuestion.style.ts
src/pages/FrequentlyAskedQuestion/FrequentlyAskedQuestion.tsx
src/styles/colors.ts

refactor of faq page

---

src/components/Services/Services.styles.tsx
src/components/Services/Services.tsx
src/ui/Section/section.styles.ts

fix: section ui  component

---

src/ui/InputSearch/InputSearch.styles.ts
src/ui/MultiSelect/MultiSelect.styles.ts

change color

---

src/pages/Blog/Blog.styles.ts
src/pages/Blog/Blog.tsx
src/routes/AppRouter.tsx

chore: blog structure

---

src/pages/Blog/Blog.styles.ts
src/pages/Blog/Blog.tsx

add: title hero in blog

---

src/pages/LetsLearn/LetsLearn.tsx

skeleton created

---

src/ui/Section/section.styles.ts

section padding fixed

---

src/components/ContactUs/FormContactUs/FormContactUs.tsx

change name of recaptcha key

---

src/ui/MultiSelect/MultiSelect.styles.ts
src/ui/MultiSelect/MultiSelect.tsx

display multiselect corrected

---

src/pages/Services/Services.tsx
src/pages/Services/ServicesHero/ServicesHero.styles.ts
src/pages/Services/ServicesHero/ServicesHero.tsx

services hero implemented

---

src/components/Clients/Clients.styles.ts
src/components/Clients/Clients.tsx

check it out!
Try to be honest my friends

chore: hide see more button

---

src/ui/BodyContainer/BodyContainer.styles.ts
src/ui/BodyContainer/BodyContainer.tsx
src/ui/Container/Container.styles.ts

- BodyContainer component created
- Padding from container removed

feat: body container component implemented

---

src/pages/PageNotFound/PageNotFound.style.ts
src/pages/PageNotFound/PageNotFound.tsx
src/ui/BodyContainer/BodyContainer.styles.ts
src/ui/Container/Container.styles.ts

✅PageNotFound page height corrected
✅Added max-width to Container component

PageNotFound page height corrected

---

src/components/Footer/Footer.data.tsx
src/components/Footer/Footer.styles.ts
src/components/Footer/Footer.tsx

✔  Now a function is used that returns the current year for the copyright.
✔  Footer padding fixed.
✔  The link to the portfolio was removed.
✔  Added a path to the default Home for "Conditions of use".

Now a function is used that returns the current year for the copyright.

---

src/pages/Home/Home.tsx
src/ui/BodyContainer/BodyContainer.styles.ts

- Body container flex direction change to column

fix: add flex direction column to bodyContainer

---

src/components/ContactUs/ContactUs.styles.ts
src/components/ContactUs/ContactUs.tsx
src/components/ContactUs/ContactUsInformation/ContactUsContent/ContactUsContent.styles.ts
src/components/ContactUs/ContactUsInformation/ContactUsContent/ContactUsContent.tsx
src/components/ContactUs/ContactUsInformation/ContactUsInformation.styles.ts
src/components/ContactUs/FormContactUs/FormContactUs.styles.ts
src/components/SocialMedia/SocialMedia.styles.ts
src/lang/en.json
src/lang/es.json

fix(contact-us):  resolved spacing and text problems

---

src/components/Hero/Hero.styles.ts
src/components/Hero/Hero.tsx

fix(hero): image positioning and component spacing

---

.gitignore
pnpm-lock.yaml
src/lang/en.json
src/lang/es.json
src/pages/PageNotFound/PageNotFound.style.ts
src/pages/PageNotFound/PageNotFound.tsx

fix(page not found): colors and language change

---

src/pages/PageNotFound/PageNotFound.style.ts
src/pages/PageNotFound/PageNotFound.tsx

Fixed focus design and added active status to the `Go To Home` button on 404 Page.

fix: Corrected Go To Home button styles.

---

src/components/Hero/Hero.styles.ts
src/components/Hero/Hero.tsx
src/components/Hero/socialMediaBar/SocialMediaBar.styles.ts
src/components/Hero/socialMediaBar/SocialMediaBar.tsx

fix: fixed hero section of the home page.

---

src/components/AboutUs/Founders/Founders.data.ts
src/components/AboutUs/Team/Team.data.ts

- Move Ricardo from Founders to Team group

refactor: move Ricardo from Founders to Team

---

src/components/Clients/Clients.styles.ts
src/components/Clients/Clients.tsx

Fixed padding and removed button

fix(services section): fixed padding and removed button

---

src/components/Header/Header.styles.ts
src/components/Header/Header.tsx
src/ui/Select/Select.styles.ts
src/ui/Select/Select.tsx

- `Contact Us Button` : Changed its href to "/contact-us", added its active and focus.
- `Language Change Button` : Active and focus design was added.
- `Language Change Dropdown` : Its border radius was corrected, its drop-shadow was added and hover was added to its options.

fix(header): Styling corrected

---

src/components/ContactUs/ContactUsInformation/ContactUsInformation.tsx
src/components/Hero/Hero.styles.ts
src/components/Hero/socialMediaBar/SocialMediaBar.styles.ts
src/components/Hero/socialMediaBar/SocialMediaBar.tsx
src/components/SocialMedia/SocialMedia.tsx

- The Twitch social network button was added to the `Hero Section`, `Footer` and Information of `Contact Us`.
- The `gap` between social media buttons on mobile was reduced.

task: added Twitch button network

---

src/components/FaqCard/FaqCard.styles.ts
src/components/FaqCard/FaqCard.tsx
src/components/StillHaveQuestion/StillHaveQuestion.styles.ts
src/components/StillHaveQuestion/StillHaveQuestion.tsx
src/lang/en.json
src/lang/es.json
src/pages/FrequentlyAskedQuestion/FrequentlyAskedQuestion.data.ts
src/pages/FrequentlyAskedQuestion/FrequentlyAskedQuestion.style.ts
src/pages/FrequentlyAskedQuestion/FrequentlyAskedQuestion.tsx

I solved many problems
There are design, unnecessary styles, translation and code refactor.

refactor FAQ page

---

src/components/Footer/Footer.data.tsx
src/components/Hero/Hero.styles.ts
src/components/Hero/Hero.tsx
src/routes/router.tsx

Contact us page was enabled in router links and footer

add: contact us page to the router and buttons

---

src/ui/Select/Select.styles.ts

Minimum width was added to circle in select componente to avoid deformations in circle

styles(Select.styles): add min width to ensure circle in select remains in circle shape

---

src/components/ContactUs/ContactUsInformation/ContactUsContent/ContactUsContent.tsx
src/components/Footer/Footer.tsx
src/context/constants/constans.ts
src/utils/formatters/formatters.ts

Company's phone number and email updated with the current and valid information.

fix(Footer&ContacUsContent): phone and email updated

---

src/styles/colors.ts

I found colors missing in the color palette, I added all the colors available in colors.ts

fix(colors): add colors missing

---

src/components/Hero/socialMediaBar/SocialMediaBar.tsx
src/components/SocialMedia/SocialMedia.tsx

Swap the Instagram button for the Linkedin button, leaving the rest of the buttons in their original place.

refactor: reorder social media buttons

---

src/pages/TermsOfService/TermsOfService.tsx

Add functionality to Term of Service with Intersection Observer

feat: add functionality to term of service with intersection observer

---

.gitignore
src/components/ContactUs/ContactUs.styles.ts
src/components/ContactUs/ContactUs.tsx
src/components/Header/Header.tsx
src/pages/ContactUs/ContactUs.styles.ts
src/ui/ButtonLink/ButtonLink.styles.tsx
src/ui/ButtonLink/ButtonLink.tsx
src/ui/Textarea/Textarea.styles.ts

Fix Contact Us page reload using router-dom NavLink component via custom ButtonLink component.
Contact Us page reload via Header button.
Use href on the anchor element of the Contact Us button, which caused reload.
Use router-dom NavLink component via custom ButtonLink component.

fix: reload contact us page

---

src/components/ContactUs/ContactUsInformation/ContactUsContent/ContactUsContent.tsx

Change the calendar of the `binland.contacto@gmail.com` account of calendly to `contact@binland.dev`.

chore: change calendly calendar

---

public/robots.txt
public/sitemap.xml

Add the sitemap.xml file and change the robots.txt file to improve SEO.

chore: add sitemap file and change robots file

---

index.html

chore: change index title

---

src/components/AboutUs/Founders/Founders.data.ts
src/lang/en.json
src/lang/es.json

Please include a summary, motivation and or context of the change and which issue is fixed.
Remove if not necessary
Remove if not necessary
Remove if not necessary
- [X ] Chore

chore: hide networks and change rol

---

src/components/AboutUs/Founders/Founders.data.ts
src/components/AboutUs/Team/Team.data.ts
src/components/Hero/Hero.styles.ts
src/components/Services/ServicesContent/ServicesContent.tsx

Please include a summary, motivation and or context of the change and which issue is fixed.
Remove if not necessary
Remove if not necessary
Remove if not necessary

small changes to improve the UI

---

lefthook.yml
src/components/Clients/Clients.styles.ts
src/components/Clients/Clients.tsx
vite.config.ts

- Implement redesign of clients section on home page
- Implement server config
- Change pre-commit (Formatting is applied to all files instead of just modified ones).

feat: home clients redesign

---

README.md

chore: change Readme file

---

src/components/Forms/ComplaintsBookForm/ComplaintsBookForm.tsx
src/lang/en.json
src/lang/es.json
src/pages/ComplaintsBook/ComplaintsBook.styles.ts
src/pages/ComplaintsBook/ComplaintsBook.tsx

- Implement confirmation view for virtual complaint book form

feat: implement confirmation view for virtual complaint book form

---

src/components/Forms/ComplaintsBookForm/ComplaintsBookForm.schema.ts

- Add regex-based email validation to virtual complaint book form
- Resolution of QA
|DOC | DATE | N°|
|--|---|----|
| [link](https://docs.google.com/document/d/1L4SmxMAtB8RQAPszQTr3BVSaxdlm9vCCO6ZqxhUJaPM/edit?tab=t.0) | 02 - Julio - 2025| `#0001` |

fix: add regex-based email validation to virtual complaint book form

---

src/components/Banner/Banner.styles.ts
src/components/Banner/Banner.tsx

- Update projects page banner design with blob lights

feat: update projects page banner design with blob lights
